# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f33a7c272abb9e665f6f8ce7e174045e806f9ac81dd99e8bd3c94f5a45e8e52f55af94acde62a7aa4ace0cbf3d4f83d73942a0629ebc2fb8bbaa9fe8b1d782c2

test:
  secret_key_base: ce35d28787919979506c47db058b3573c414ad7a1c190484a7b4909f3d20df18a54ebdbcad48b3a06797df25422b3ff8e1da4b1c6f6750db218f27d3db64e5b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
